spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Dhirendra@123
    url: jdbc:mysql://localhost:3306/sbms
    username: root
  jpa:
    hibernate:
      ddl-auto: update #Generate the table automatically
    show-sql: true  #whatever generated query print in console

server:
  port: 9090